blank_issues_enabled: true
contact_links:
  - name: Wiki
    url: https://github.com/ohmpatel3877/CortexStratum/wiki
    about: Check the wiki for documentation and guides
  - name: Discussion
    url: https://github.com/ohmpatel3877/CortexStratum/discussions
    about: Ask questions and discuss ideas
